### ISSUE TITLE
Citing your package

### ISSUE THREAD

**Issue by mdmould** [danielward27/flowjax#124]
I've made a lot of use of your really nice package for several projects that I hope to publish in the not-too-distant future. Would you consider making it citable, e.g., via a Zenodo DOI (https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content, which integrates nicely with GitHub releases)?

**Comment by danielward27** [comment]
Thanks for the suggestion, I'm happy to hear that you've found the package useful for your projects!

I have linked the project with Zenodo and added a short example bibtex citation to the readme in https://github.com/danielward27/flowjax/pull/126 (merged into main). I'll close this for now, but let me know if you have any further thoughts or suggestions.
