### ISSUE TITLE
Add Variational Inference training helper

### ISSUE THREAD

**Issue by Tennessee-Wallaceh** [danielward27/flowjax#60]
Similar to the `train_flow` helper function, it would be useful to have a `fit_flow_vi` (naming), helper function.
For now this can be a simple implementation, with potentially more robust implementations to follow (such as https://arxiv.org/pdf/1802.02538.pdf).

@danielward27  I am working on this on my fork [60-add-vi-helper](https://github.com/Tennessee-Wallaceh/flowjax/tree/60-add-vi-helper)

**Comment by danielward27** [comment]
Nice, that would be really good! Hopefully we can add a notebook example too in the docs? I've just added a new release, that (unfortunately) includes some breaking changes (the significant ones listed here  https://github.com/danielward27/flowjax/releases/tag/v7.0.0), but hopefully improves things significantly overall. Hopefully the changes don't cause you too much trouble, and let me know if you have any questions.

**Comment by Tennessee-Wallaceh** [comment]
Closed in https://github.com/danielward27/flowjax/pull/63
