### ISSUE TITLE
flowjax not available after install

### ISSUE THREAD

**Issue by mdmould** [danielward27/flowjax#99]
Thanks for this package, along with the documentation it looks great and I'm excited to use it.

However, after installing with pip, I cannot import the package, which gives `ModuleNotFoundError: No module named 'flowjax'`. The same issue occurs when cloning and installing, then navigating away from the flowjax root directory.

To reproduce (e.g., in colab):
```
!pip install flowjax
import flowjax
```

Any ideas?

**Comment by danielward27** [comment]
Thanks! This should now be fixed in the latest release (fixed by https://github.com/danielward27/flowjax/pull/100), let me know if you have any other issues.
